config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/index'
  get 'bookmarks/new'
  get 'bookmarks/create'
  get 'lists/index'
  get 'lists/new'
  get 'lists/create'
  get 'lists/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [ :index, :new, :create, :show ] do
    resources :bookmarks, only: [:index, :new, :create, ]
  end
  delete 'bookmark/:id', to: 'bookmarks#destroy', as: :bookmark
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :list, presence: true
  validates :movie, presence: true
  validates :movie, uniqueness: { scope: :list, message: "movie already associated with the list" }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = Bookmark.select { |bookmark| bookmark.list = @list }
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [ @list, @bookmark]  do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<%= render "form", bookmark: @bookmark %>

app/views/bookmarks/show.html.erb
<h1><%= @bookmark.movie.title %></h1>
<p>Comment: <%= @bookmark.comment %></p>
<p>Rating: <%= @bookmark.rating %></p>
<p>Category: <%= @bookmark.list.name %></p>

app/views/layouts/_navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <%= link_to "#", class: "navbar-brand" do %>
          <%= cl_image_tag("aul8hkgw180yta6zj9w9", width: 64, height: 64, crop: :fill) %>
        <% end %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <%= link_to "Add New List", new_list_path, class: "nav-link" %>
              </li>
          </ul>
        </div>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



    <%= yield %>
  </body>
</html>

app/views/lists/_banner.html.erb
<div class="banner h-500 text-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path("qrdpwawowlwcj92wdvca", crop: :fill) %>')">
  <div class="container">
    <h1>Have a look at my list of movies!</h1>
    <p>Enjoy with popcorn and friends</p>
  </div>
</div>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.button :submit%>
  <%= f.input :photo, as: :file %>
<% end %>

app/views/lists/_navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <%= link_to "#", class: "navbar-brand" do %>
          <%= cl_image_tag("aul8hkgw180yta6zj9w9", width: 64, height: 64, crop: :fill) %>
        <% end %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <%= link_to "Add New List", new_list_path, class: "nav-link" %>
              </li>
          </ul>
        </div>
      </div>
  </div>

app/views/lists/index.html.erb
<%= render 'navbar', list: @list %>
<%= render 'banner', list: @list %>

  <div class="cards">
    <% if @lists.length == 0 %>
      <h1><%= "No lists have been created yet"%></h1><br>
    <% else %>
      <% @lists.each do |list|%>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
           <%= link_to list.name, list_path(list)%>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<div class="banner h-500 text-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>')">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>



<%= link_to "Create New Bookmark", new_list_bookmark_path(@list), class: 'btn btn-primary'%>

<h1>Lists#Bookmarks</h1>
<% @list.bookmarks.each do |bookmark|%>
  <div class="cards">
    <div class="card-trip">
      <%= link_to list_bookmarks_path(@list) do %>
        <img src="<%=bookmark.movie.poster_url%>" alt="poster" >
      <% end %>
      <div class="card-trip-infos">
        <div>
          <h3><%= bookmark.movie.title %></h3>
          <p><%= bookmark.movie.overview %></p>
        </div>
        <h2 class="card-trip-pricing"></h2>
      </div>
    </div>
  </div>



  <li><%= link_to bookmark.movie.title, list_bookmarks_path(@list) %> <%= link_to "Delete", bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure?" } %>
</li>
<% end %>